plugins {
	id "net.fabricmc.fabric-loom" version "1.16-SNAPSHOT"
	id "io.github.p03w.machete" version "1.2.0"
}

version = project.mod_version
group = project.maven_group

repositories {}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.fabric_loader}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api}"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 25
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
    withSourcesJar()
}
