# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
mod_version = 0.3.1+26.2
maven_group = ru.pinkgoosik
archives_base_name = better-end-sky

# Dependencies | Check these on https://fabricmc.net/develop
minecraft_version = 26.2
fabric_loader = 0.19.3
fabric_api = 0.152.1+26.2
