# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
mod_version = 0.3.0+26.1
maven_group = ru.pinkgoosik
archives_base_name = better-end-sky

# Dependencies | Check these on https://fabricmc.net/develop
minecraft_version = 26.1
fabric_loader = 0.19.2
fabric_api = 0.145.1+26.1
