# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
mod_version = 0.3.1+26.3
maven_group = ru.pinkgoosik
archives_base_name = better-end-sky

# Dependencies | Check these on https://fabricmc.net/develop
minecraft_version = 26.3-rc-3
fabric_loader = 0.19.5
fabric_api = 0.160.5+26.3

