license="MIT"
[[mods]] #mandatory
modId="better_end_sky" #mandatory
version="${version}" #mandatory
displayName="Better End Sky" #mandatory
authors="BetterX Team"
[[mixins]]
config="better_end_sky.mixins.json"
