license="MIT"
[[mods]] #mandatory
modId="better_end_sky" #mandatory
version="0.3.1+26.2" #mandatory
displayName="Better End Sky" #mandatory
authors="BetterX Team"
[[mixins]]
config="better_end_sky.mixins.json"
